# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
branches:
  only:
  - master
  - develop
  - /fix\/.*/
  - /feature\/.*/
  - /release\/.*/

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/flow-test.xcworkspace -scheme flow-test-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty

- pod lib lint
